version: "3.9"

services:
  api:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  scheduler:
    entrypoint: ["bash", "-c", "while true; do python app/extrair_dados.py; for f in /app/dados/Manobra_*.xlsx; do echo '[INFO] Importando $f...' && python -m app.import_excel $f; done; sleep 10; done"]
